project:
  type: website
  output-dir: docs

website:
  title: "Mason Posner"
  favicon: media/logo.jpg
  navbar:
    right:
      - href: index.qmd
        text: About
      - research.qmd
      - publications.qmd
      - teaching.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

