project:
  type: website
  output-dir: docs

website:
  title: "Mason Posner"
  favicon: media/logo.jpg
  navbar:
    left: 
     - href: index.qmd
       text: Bio
    right:
      - research.qmd
      - href: people.qmd
        text: Lab Members
      - publications.qmd
      - teaching.qmd
      - news.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

